# .github/workflows/ci-cd-pipeline.yml

name: CI/CD Pipeline for Node.js App with Docker

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: self-hosted  # Specify the type of runner (can also use self-hosted runners)
    env: 
      https_proxy: http://192.168.56.1:10810
      http_proxy: http://192.168.56.1:10810
      
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx (optional, helps with building multi-platform images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ci-cd-nodejs-app:${{ github.run_id }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/ci-cd-nodejs-app:${{ github.run_id }} ${{ secrets.DOCKER_USERNAME }}/ci-cd-nodejs-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/ci-cd-nodejs-app:latest

      # Step 4: Copy docker-compose.yml file to /mnt directory
      - name: Copy docker-compose.yml to runner's /mnt directory
        run: |
          # Copy the docker-compose.yml file from the repository to /mnt directory on the runner
          cp docker-compose.yml /mnt/docker-compose.yml

      # Step 5: Run Docker Compose to start the container
      - name: Deploy Docker Containers with Docker Compose
        run: |
          # Change to the /mnt directory where the docker-compose.yml is copied
          cd /mnt
          # Run docker-compose to bring up containers in detached mode
          docker compose up -d
          
      # Step 6: Verify Docker container is running
      - name: Verify Docker container status
        run: |
          # Check the status of the running Docker containers
          docker ps
